//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMaster
    {
        public System.Guid Id { get; set; }
        public string KodeDC { get; set; }
        public string NamaDC { get; set; }
        public string KodeToko { get; set; }
        public string NamaToko { get; set; }
    }
}
