//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserTokens = new HashSet<UserToken>();
        }
    
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public string LastLogin { get; set; }
    
        public virtual ICollection<UserToken> UserTokens { get; set; }
    }
}
